const bodyPartsVocabulary = [
  { word: "head", meaning: "cabeça" },
  { word: "face", meaning: "rosto" },
  { word: "hair", meaning: "cabelo" },
  { word: "forehead", meaning: "testa" },
  { word: "eye", meaning: "olho" },
  { word: "eyebrow", meaning: "sobrancelha" },
  { word: "eyelash", meaning: "cílios" },
  { word: "ear", meaning: "orelha" },
  { word: "nose", meaning: "nariz" },
  { word: "mouth", meaning: "boca" },
  { word: "lip", meaning: "lábio" },
  { word: "teeth", meaning: "dentes" },
  { word: "tongue", meaning: "língua" },
  { word: "neck", meaning: "pescoço" },
  { word: "shoulder", meaning: "ombro" },
  { word: "arm", meaning: "braço" },
  { word: "elbow", meaning: "cotovelo" },
  { word: "wrist", meaning: "pulso" },
  { word: "hand", meaning: "mão" },
  { word: "finger", meaning: "dedo da mão" },
  { word: "thumb", meaning: "polegar" },
  { word: "chest", meaning: "peito" },
  { word: "back", meaning: "costas" },
  { word: "stomach / belly", meaning: "estômago / barriga" },
  { word: "waist", meaning: "cintura" },
  { word: "hip", meaning: "quadril" },
  { word: "leg", meaning: "perna" },
  { word: "knee", meaning: "joelho" },
  { word: "ankle", meaning: "tornozelo" },
  { word: "foot", meaning: "pé" },
  { word: "toe", meaning: "dedo do pé" },
  { word: "skin", meaning: "pele" },
  { word: "bone", meaning: "osso" },
  { word: "muscle", meaning: "músculo" }
] as const;
