export const cityPlacesVocabulary = [
  { word: "bank", meaning: "banco", description: "Place to keep or take money" },
  { word: "supermarket", meaning: "supermercado", description: "Large store selling food and other items" },
  { word: "grocery store", meaning: "mercado pequeno", description: "Small shop selling food and everyday items" },
  { word: "pharmacy / drugstore", meaning: "farmácia", description: "Place to buy medicine" },
  { word: "hospital", meaning: "hospital", description: "Place for medical care" },
  { word: "clinic", meaning: "clínica", description: "Smaller medical center" },
  { word: "park", meaning: "parque", description: "Green outdoor area for recreation" },
  { word: "playground", meaning: "parquinho", description: "Outdoor area with equipment for children" },
  { word: "restaurant", meaning: "restaurante", description: "Place where you can eat meals" },
  { word: "café", meaning: "cafeteria", description: "Small place to have coffee and snacks" },
  { word: "library", meaning: "biblioteca", description: "Place to read or borrow books" },
  { word: "bookstore", meaning: "livraria", description: "Shop where you buy books" },
  { word: "cinema / movie theater", meaning: "cinema", description: "Place to watch movies" },
  { word: "gym", meaning: "academia", description: "Place to exercise" },
  { word: "stadium", meaning: "estádio", description: "Large place for sports or concerts" },
  { word: "school", meaning: "escola", description: "Place where children learn" },
  { word: "university / college", meaning: "universidade", description: "Higher education institution" },
  { word: "museum", meaning: "museu", description: "Place with art or historical items" },
  { word: "shopping mall", meaning: "shopping center", description: "Large building with many shops" },
  { word: "bus stop", meaning: "ponto de ônibus", description: "Where you wait for the bus" },
  { word: "train station", meaning: "estação de trem", description: "Where you catch a train" },
  { word: "subway station", meaning: "estação de metrô", description: "Where you take the metro" },
  { word: "airport", meaning: "aeroporto", description: "Where planes arrive and depart" },
  { word: "hotel", meaning: "hotel", description: "Place to stay when traveling" },
  { word: "hostel", meaning: "hostel", description: "Cheap place to stay, often sharing rooms" },
  { word: "bakery", meaning: "padaria", description: "Place to buy bread and pastries" },
  { word: "butcher", meaning: "açougue", description: "Shop selling meat" },
  { word: "church", meaning: "igreja", description: "Christian place of worship" },
  { word: "temple", meaning: "templo", description: "Place of worship for some religions" },
  { word: "mosque", meaning: "mesquita", description: "Muslim place of worship" },
  { word: "post office", meaning: "correios", description: "Send letters and packages" },
  { word: "police station", meaning: "delegacia", description: "Place for police services" },
  { word: "fire station", meaning: "corpo de bombeiros", description: "Base for firefighters" },
  { word: "hair salon / barber shop", meaning: "salão de beleza / barbearia", description: "Place to cut or style hair" }
] as const;