const clothesVocabulary = [
  { word: "shirt", meaning: "camisa" },
  { word: "t-shirt", meaning: "camiseta" },
  { word: "blouse", meaning: "blusa feminina" },
  { word: "sweater", meaning: "suéter" },
  { word: "jacket", meaning: "jaqueta" },
  { word: "coat", meaning: "casaco" },
  { word: "pants / trousers", meaning: "calças" },
  { word: "shorts", meaning: "shorts" },
  { word: "jeans", meaning: "calça jeans" },
  { word: "dress", meaning: "vestido" },
  { word: "skirt", meaning: "saia" },
  { word: "suit", meaning: "terno" },
  { word: "tie", meaning: "gravata" },
  { word: "scarf", meaning: "cachecol / lenço" },
  { word: "hat", meaning: "chapéu" },
  { word: "cap", meaning: "boné" },
  { word: "shoes", meaning: "sapatos" },
  { word: "sneakers", meaning: "tênis" },
  { word: "boots", meaning: "botas" },
  { word: "socks", meaning: "meias" },
  { word: "belt", meaning: "cinto" },
  { word: "gloves", meaning: "luvas" }
] as const;
