export const dailyRoutineVocabulary = [
  { word: "wake up", meaning: "acordar", description: "To stop sleeping in the morning" },
  { word: "get up", meaning: "levantar", description: "To get out of bed after waking up" },
  { word: "stretch", meaning: "espreguiçar-se", description: "To extend your body after waking up" },
  { word: "brush teeth", meaning: "escovar os dentes", description: "To clean your teeth" },
  { word: "wash face", meaning: "lavar o rosto", description: "To clean your face with water" },
  { word: "take a shower", meaning: "tomar banho", description: "To wash your whole body under running water" },
  { word: "get dressed", meaning: "vestir-se", description: "To put on clothes" },
  { word: "comb hair", meaning: "pentear o cabelo", description: "To make your hair neat with a comb" },
  { word: "make the bed", meaning: "arrumar a cama", description: "To straighten your bed after sleeping" },
  { word: "have breakfast", meaning: "tomar café da manhã", description: "To eat the first meal of the day" },
  { word: "go to work", meaning: "ir ao trabalho", description: "To travel to your job" },
  { word: "go to school", meaning: "ir à escola", description: "To travel to your classes" },
  { word: "check emails", meaning: "verificar emails", description: "To read your electronic messages" },
  { word: "study", meaning: "estudar", description: "To learn or review something" },
  { word: "have lunch", meaning: "almoçar", description: "To eat your midday meal" },
  { word: "work", meaning: "trabalhar", description: "To do your job or tasks" },
  { word: "have a meeting", meaning: "ter uma reunião", description: "To talk with others for work or planning" },
  { word: "take a break", meaning: "fazer uma pausa", description: "To rest for a short time during work" },
  { word: "run errands", meaning: "resolver coisas na rua / afazeres", description: "To do small tasks like going to the bank or store" },
  { word: "do chores", meaning: "fazer tarefas domésticas", description: "To clean or organize your house" },
  { word: "cook dinner", meaning: "cozinhar o jantar", description: "To prepare food for the evening meal" },
  { word: "have dinner", meaning: "jantar", description: "To eat your evening meal" },
  { word: "walk the dog", meaning: "passear com o cachorro", description: "To take your pet outside for exercise" },
  { word: "watch TV", meaning: "assistir TV", description: "To look at programs on television" },
  { word: "read a book", meaning: "ler um livro", description: "To look at written pages and understand them" },
  { word: "browse the internet", meaning: "navegar na internet", description: "To look for things online" },
  { word: "play video games", meaning: "jogar videogame", description: "To use an electronic game for fun" },
  { word: "talk on the phone", meaning: "falar ao telefone", description: "To speak with someone by calling them" },
  { word: "meet friends", meaning: "encontrar amigos", description: "To spend time with people you like" },
  { word: "go for a walk", meaning: "fazer uma caminhada", description: "To move slowly on foot outdoors" },
  { word: "exercise", meaning: "fazer exercício", description: "To move your body to keep healthy" },
  { word: "take a nap", meaning: "tirar um cochilo", description: "To sleep for a short time during the day" },
  { word: "do homework", meaning: "fazer lição de casa", description: "To complete school tasks at home" },
  { word: "take a shower (before bed)", meaning: "tomar banho (antes de dormir)", description: "To wash before going to sleep" },
  { word: "go to bed", meaning: "ir para a cama", description: "To lie down to sleep at night" },
  { word: "sleep", meaning: "dormir", description: "To rest with your eyes closed at night" },
  { word: "set the alarm", meaning: "programar o despertador", description: "To choose the time your alarm will ring" },
  { word: "meditate", meaning: "meditar", description: "To sit quietly and focus your mind" },
  { word: "relax", meaning: "relaxar", description: "To rest and feel calm" },
  { word: "have a snack", meaning: "fazer um lanche", description: "To eat a small amount of food between meals" }
] as const;