export const emotionsVocabulary = [
  { word: "happy", meaning: "feliz", description: "Feeling joy or pleasure" },
  { word: "sad", meaning: "triste", description: "Feeling unhappy or sorrowful" },
  { word: "angry", meaning: "bravo / com raiva", description: "Feeling strong displeasure or rage" },
  { word: "worried", meaning: "preocupado", description: "Thinking that something bad might happen" },
  { word: "excited", meaning: "animado", description: "Feeling very happy and enthusiastic" },
  { word: "bored", meaning: "entediado", description: "Feeling that nothing is interesting" },
  { word: "scared", meaning: "com medo", description: "Afraid that something bad might happen" },
  { word: "surprised", meaning: "surpreso", description: "Feeling amazed because something was unexpected" },
  { word: "nervous", meaning: "nervoso", description: "Feeling worried or uneasy about something" },
  { word: "proud", meaning: "orgulhoso", description: "Feeling pleased because of something you did or have" },
  { word: "embarrassed", meaning: "envergonhado", description: "Feeling shy or ashamed in a social situation" },
  { word: "tired", meaning: "cansado", description: "Feeling that you need to rest or sleep" },
  { word: "relaxed", meaning: "relaxado", description: "Calm and free from stress" },
  { word: "confused", meaning: "confuso", description: "Not understanding what is happening" },
  { word: "disappointed", meaning: "decepcionado", description: "Feeling sad because something didn't meet expectations" },
  { word: "calm", meaning: "calmo", description: "Not feeling angry, nervous, or excited" },
  { word: "hopeful", meaning: "esperançoso", description: "Believing that good things will happen" },
  { word: "hopeless", meaning: "sem esperança", description: "Believing that nothing good will happen" },
  { word: "anxious", meaning: "ansioso", description: "Feeling nervous and worried about something" },
  { word: "annoyed", meaning: "irritado", description: "Slightly angry or bothered by something" },
  { word: "frustrated", meaning: "frustrado", description: "Upset because you can’t do something you want" },
  { word: "jealous", meaning: "com ciúmes", description: "Afraid of losing something or someone to another person" },
  { word: "lonely", meaning: "solitário", description: "Feeling sad because you are alone" },
  { word: "shy", meaning: "tímido", description: "Feeling nervous around other people" },
  { word: "energetic", meaning: "cheio de energia", description: "Full of energy and ready to do things" },
  { word: "grateful", meaning: "grato", description: "Feeling thankful for something" },
  { word: "guilty", meaning: "culpado", description: "Feeling bad because you think you did something wrong" },
  { word: "overwhelmed", meaning: "sobrecarregado", description: "Feeling that you have too many things to deal with" },
  { word: "refreshed", meaning: "renovado", description: "Feeling fresh and energetic after resting" },
  { word: "relieved", meaning: "aliviado", description: "Feeling relaxed because something bad didn't happen" },
  { word: "satisfied", meaning: "satisfeito", description: "Feeling pleased because something is enough or good" },
  { word: "shocked", meaning: "chocado", description: "Very surprised and sometimes upset by something unexpected" },
  { word: "amazed", meaning: "impressionado, maravilhado", description: "Very surprised and impressed by something" },
  { word: "curious", meaning: "curioso", description: "Wanting to learn or know more about something" },
  { word: "determined", meaning: "determinado", description: "Wanting to do something very much and not give up" },
  { word: "doubtful", meaning: "duvidoso", description: "Not sure if something is true or will happen" },
  { word: "eager", meaning: "ansioso (positivo)", description: "Excited and keen to do or get something" },
  { word: "indifferent", meaning: "indiferente", description: "Not caring about something" },
  { word: "inspired", meaning: "inspirado", description: "Feeling motivated by something or someone" },
  { word: "upset", meaning: "chateado", description: "Unhappy or disappointed because of something" },
  { word: "uncomfortable", meaning: "desconfortável", description: "Feeling uneasy or awkward" },
  { word: "uneasy", meaning: "inquieto", description: "Feeling worried or nervous" }
] as const;