export const familyVocabulary = [
  { word: "mother / mom", meaning: "mãe", description: "The woman who gave birth to you" },
  { word: "father / dad", meaning: "pai", description: "The man who raised or gave life to you" },
  { word: "parents", meaning: "pais", description: "Your mother and father together" },
  { word: "daughter", meaning: "filha", description: "A female child" },
  { word: "son", meaning: "filho", description: "A male child" },
  { word: "sister", meaning: "irmã", description: "A female sibling" },
  { word: "brother", meaning: "irmão", description: "A male sibling" },
  { word: "siblings", meaning: "irmãos", description: "Brothers and/or sisters" },
  { word: "uncle", meaning: "tio", description: "Your parent's brother" },
  { word: "aunt", meaning: "tia", description: "Your parent's sister" },
  { word: "cousin", meaning: "primo / prima", description: "The child of your aunt or uncle" },
  { word: "grandmother / grandma", meaning: "avó", description: "Your mother's or father's mother" },
  { word: "grandfather / grandpa", meaning: "avô", description: "Your mother's or father's father" },
  { word: "grandparents", meaning: "avós", description: "Your grandparents together" },
  { word: "grandchild", meaning: "neto(a)", description: "The child of your child" },
  { word: "grandson", meaning: "neto", description: "A male grandchild" },
  { word: "granddaughter", meaning: "neta", description: "A female grandchild" },
  { word: "husband", meaning: "marido", description: "The man you are married to" },
  { word: "wife", meaning: "esposa", description: "The woman you are married to" },
  { word: "nephew", meaning: "sobrinho", description: "Your brother’s or sister’s son" },
  { word: "niece", meaning: "sobrinha", description: "Your brother’s or sister’s daughter" },
  { word: "in-laws", meaning: "parentes por afinidade", description: "Family from your spouse's side" },
  { word: "father-in-law", meaning: "sogro", description: "Your husband's or wife's father" },
  { word: "mother-in-law", meaning: "sogra", description: "Your husband's or wife's mother" },
  { word: "brother-in-law", meaning: "cunhado", description: "Your spouse’s brother or your sibling’s husband" },
  { word: "sister-in-law", meaning: "cunhada", description: "Your spouse’s sister or your sibling’s wife" },
  { word: "stepfather", meaning: "padrasto", description: "The man married to your mother but not your biological father" },
  { word: "stepmother", meaning: "madrasta", description: "The woman married to your father but not your biological mother" },
  { word: "stepsister", meaning: "meia-irmã / irmã por afinidade", description: "The daughter of your step-parent" },
  { word: "stepbrother", meaning: "meio-irmão / irmão por afinidade", description: "The son of your step-parent" },
  { word: "fiancé / fiancée", meaning: "noivo / noiva", description: "Person you are engaged to marry" },
  { word: "boyfriend", meaning: "namorado", description: "A man you are romantically involved with" },
  { word: "girlfriend", meaning: "namorada", description: "A woman you are romantically involved with" },
  { word: "friend", meaning: "amigo(a)", description: "Someone you like and spend time with" },
  { word: "close friend", meaning: "amigo próximo", description: "A very good friend" },
  { word: "best friend", meaning: "melhor amigo", description: "Your closest friend" },
  { word: "colleague", meaning: "colega de trabalho", description: "Someone you work with" },
  { word: "neighbor", meaning: "vizinho", description: "A person who lives near you" },
  { word: "roommate", meaning: "companheiro de quarto", description: "Someone you share a room or apartment with" }
] as const;