export const foodAndDrinksVocabulary = [
  { word: "bread", meaning: "pão", description: "Baked food made from flour and water" },
  { word: "rice", meaning: "arroz", description: "Small white or brown grains, staple food" },
  { word: "pasta", meaning: "macarrão", description: "Italian dish made from dough" },
  { word: "meat", meaning: "carne", description: "Flesh of animals used as food" },
  { word: "chicken", meaning: "frango", description: "Meat from a domestic bird" },
  { word: "beef", meaning: "carne bovina", description: "Meat from cattle" },
  { word: "pork", meaning: "carne suína", description: "Meat from pigs" },
  { word: "fish", meaning: "peixe", description: "Animal living in water, eaten as food" },
  { word: "seafood", meaning: "frutos do mar", description: "Sea animals used as food" },
  { word: "cheese", meaning: "queijo", description: "Dairy product made from milk" },
  { word: "milk", meaning: "leite", description: "White liquid from cows or other animals" },
  { word: "water", meaning: "água", description: "Clear liquid essential for life" },
  { word: "juice", meaning: "suco", description: "Liquid from fruits or vegetables" },
  { word: "soda", meaning: "refrigerante", description: "Carbonated sweet drink" },
  { word: "coffee", meaning: "café", description: "Brewed drink from roasted beans" },
  { word: "tea", meaning: "chá", description: "Hot or cold drink made from leaves" },
  { word: "fruit", meaning: "fruta", description: "Edible sweet part of a plant" },
  { word: "apple", meaning: "maçã", description: "Round fruit with red or green skin" },
  { word: "banana", meaning: "banana", description: "Long yellow fruit" },
  { word: "orange", meaning: "laranja", description: "Citrus fruit with orange skin" },
  { word: "grape", meaning: "uva", description: "Small round fruit used to make wine" },
  { word: "vegetable", meaning: "legume / vegetal", description: "Edible plant or part of a plant" },
  { word: "salad", meaning: "salada", description: "Cold dish of mixed vegetables" },
  { word: "dessert", meaning: "sobremesa", description: "Sweet food eaten after a meal" },
  { word: "cake", meaning: "bolo", description: "Sweet baked dessert" },
  { word: "ice cream", meaning: "sorvete", description: "Frozen sweet dairy dessert" },
  { word: "snack", meaning: "lanche / petisco", description: "Small amount of food between meals" },
  { word: "egg", meaning: "ovo", description: "Laid by birds, used as food" },
  { word: "butter", meaning: "manteiga", description: "Fat made from cream" },
  { word: "honey", meaning: "mel", description: "Sweet substance made by bees" },
  { word: "bread roll", meaning: "pãozinho / pão francês", description: "Small round loaf of bread" }
] as const;