const personalityVocabulary = [
  { word: "friendly", meaning: "amigável" },
  { word: "funny", meaning: "engraçado" },
  { word: "shy", meaning: "tímido" },
  { word: "outgoing", meaning: "extrovertido" },
  { word: "kind", meaning: "gentil" },
  { word: "polite", meaning: "educado" },
  { word: "rude", meaning: "grosseiro" },
  { word: "generous", meaning: "generoso" },
  { word: "selfish", meaning: "egoísta" },
  { word: "hard-working", meaning: "trabalhador" },
  { word: "lazy", meaning: "preguiçoso" },
  { word: "optimistic", meaning: "otimista" },
  { word: "pessimistic", meaning: "pessimista" },
  { word: "serious", meaning: "sério" },
  { word: "sensitive", meaning: "sensível" },
  { word: "cheerful", meaning: "alegre" },
  { word: "quiet", meaning: "quieto / calado" },
  { word: "talkative", meaning: "falante" },
  { word: "brave", meaning: "corajoso" },
  { word: "coward", meaning: "covarde" },
  { word: "creative", meaning: "criativo" },
  { word: "intelligent / smart", meaning: "inteligente" },
  { word: "fun", meaning: "divertido" },
  { word: "honest", meaning: "honesto" },
  { word: "patient", meaning: "paciente" },
  { word: "impatient", meaning: "impaciente" },
  { word: "calm", meaning: "calmo" },
  { word: "organized", meaning: "organizado" },
  { word: "messy", meaning: "bagunceiro" }
] as const;