export const travelAndTransportVocabulary = [
  { word: "car", meaning: "carro", description: "A road vehicle with four wheels, usually powered by an engine" },
  { word: "bus", meaning: "ônibus", description: "A large motor vehicle carrying passengers by road" },
  { word: "train", meaning: "trem", description: "A series of connected vehicles running on tracks" },
  { word: "subway / metro", meaning: "metrô", description: "An underground electric railway system in a city" },
  { word: "plane", meaning: "avião", description: "An aircraft with fixed wings for flying" },
  { word: "motorcycle / motorbike", meaning: "moto", description: "A two-wheeled motor vehicle" },
  { word: "bike / bicycle", meaning: "bicicleta", description: "A vehicle with two wheels powered by pedaling" },
  { word: "taxi / cab", meaning: "táxi", description: "A car licensed to carry passengers for a fare" },
  { word: "boat", meaning: "barco", description: "A small vessel for traveling on water" },
  { word: "ship", meaning: "navio", description: "A large vessel for traveling on water" },
  { word: "ticket", meaning: "bilhete / passagem", description: "A pass allowing entry or travel" },
  { word: "luggage", meaning: "bagagem", description: "Bags and suitcases used for travel" },
  { word: "suitcase", meaning: "mala", description: "A case for carrying clothes and belongings" },
  { word: "backpack", meaning: "mochila", description: "A bag carried on the back for travel or school" },
  { word: "departure", meaning: "partida", description: "The act of leaving a place" },
  { word: "arrival", meaning: "chegada", description: "The act of coming to a place" },
  { word: "passport", meaning: "passaporte", description: "An official document for international travel" },
  { word: "boarding pass", meaning: "cartão de embarque", description: "A document allowing a passenger to enter a plane" },
  { word: "seat", meaning: "assento", description: "A place to sit" },
  { word: "window seat", meaning: "assento na janela", description: "A seat next to the window on a plane or vehicle" },
  { word: "aisle seat", meaning: "assento no corredor", description: "A seat next to the aisle on a plane or vehicle" },
  { word: "reservation", meaning: "reserva", description: "An arrangement to have a place or service saved" },
  { word: "check-in", meaning: "check-in", description: "The process of confirming arrival at an airport or hotel" },
  { word: "hotel", meaning: "hotel", description: "A place providing lodging to travelers" },
  { word: "hostel", meaning: "hostel", description: "A budget accommodation with shared rooms" },
  { word: "map", meaning: "mapa", description: "A visual representation of an area" },
  { word: "tourist", meaning: "turista", description: "A person traveling for pleasure" },
  { word: "guidebook", meaning: "guia de viagem (livro)", description: "A book providing travel information" }
] as const;